lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: jekyll/minima@0b7ca6b
title: rknotes
author:
  name: Raiyan Kamal
minima:
  nav_pages:
    - /pages/help-needed.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/raiyankamal"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/raiyan-kamal-9877251b/"